export declare const DEFAULT_MOD_SETTINGS_V8 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<save>\n    <version major=\"4\" minor=\"8\" revision=\"0\" build=\"10\"/>\n    <region id=\"ModuleSettings\">\n        <node id=\"root\">\n            <children>\n                <node id=\"Mods\">\n                    <children>\n                        <node id=\"ModuleShortDesc\">\n                            <attribute id=\"Folder\" type=\"LSString\" value=\"GustavX\"/>\n                            <attribute id=\"MD5\" type=\"LSString\" value=\"\"/>\n                            <attribute id=\"Name\" type=\"LSString\" value=\"GustavX\"/>\n                            <attribute id=\"PublishHandle\" type=\"uint64\" value=\"0\"/>\n                            <attribute id=\"UUID\" type=\"guid\" value=\"cb555efe-2d9e-131f-8195-a89329d218ea\"/>\n                            <attribute id=\"Version64\" type=\"int64\" value=\"36028797018963968\"/>\n                        </node>\n                    </children>\n                </node>\n            </children>\n        </node>\n    </region>\n</save>";
export declare const DEFAULT_MOD_SETTINGS_V7 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<save>\n  <version major=\"4\" minor=\"7\" revision=\"1\" build=\"200\"/>\n  <region id=\"ModuleSettings\">\n    <node id=\"root\">\n      <children>\n        <node id=\"Mods\">\n          <children>\n            <node id=\"ModuleShortDesc\">\n              <attribute id=\"Folder\" type=\"LSString\" value=\"GustavDev\"/>\n              <attribute id=\"MD5\" type=\"LSString\" value=\"\"/>\n              <attribute id=\"Name\" type=\"LSString\" value=\"GustavDev\"/>\n              <attribute id=\"PublishHandle\" type=\"uint64\" value=\"0\"/>\n              <attribute id=\"UUID\" type=\"guid\" value=\"28ac9ce2-2aba-8cda-b3b5-6e922f71b6b8\"/>\n              <attribute id=\"Version64\" type=\"int64\" value=\"36028797018963968\"/>\n            </node>\n          </children>\n        </node>\n      </children>\n    </node>\n  </region>\n</save>";
export declare const DEFAULT_MOD_SETTINGS_V6 = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<save>\n  <version major=\"4\" minor=\"0\" revision=\"10\" build=\"100\"/>\n  <region id=\"ModuleSettings\">\n    <node id=\"root\">\n      <children>\n        <node id=\"ModOrder\">\n          <children/>\n        </node>\n        <node id=\"Mods\">\n          <children>\n            <node id=\"ModuleShortDesc\">\n              <attribute id=\"Folder\" type=\"LSString\" value=\"GustavDev\"/>\n              <attribute id=\"MD5\" type=\"LSString\" value=\"\"/>\n              <attribute id=\"Name\" type=\"LSString\" value=\"GustavDev\"/>\n              <attribute id=\"UUID\" type=\"FixedString\" value=\"28ac9ce2-2aba-8cda-b3b5-6e922f71b6b8\"/>\n              <attribute id=\"Version64\" type=\"int64\" value=\"36028797018963968\"/>\n            </node>\n          </children>\n        </node>\n      </children>\n    </node>\n  </region>\n</save>";
export declare const GAME_ID = "baldursgate3";
export declare const DEBUG = false;
export declare const LSLIB_URL = "https://github.com/Norbyte/lslib";
export declare const LO_FILE_NAME = "loadOrder.json";
export declare const INVALID_LO_MOD_TYPES: string[];
export declare const IGNORE_PATTERNS: any[];
export declare const MOD_TYPE_LSLIB = "bg3-lslib-divine-tool";
export declare const MOD_TYPE_BG3SE = "bg3-bg3se";
export declare const MOD_TYPE_REPLACER = "bg3-replacer";
export declare const MOD_TYPE_LOOSE = "bg3-loose";
export declare const ORIGINAL_FILES: Set<string>;
export declare const LSLIB_FILES: Set<string>;
export declare const NOTIF_IMPORT_ACTIVITY = "bg3-loadorder-import-activity";
//# sourceMappingURL=common.d.ts.map